void registrar(FILE* fp, FILE* leer, struct entrenadores entrenador, struct usuarios usuario);
void login(FILE* fp, struct entrenadores& entrenador, struct usuarios& usuario, int respuesta);
void listar(FILE* fp, struct entrenadores entrenador, struct usuarios usuario, struct Actividades actividad);
bool validPass(char contrasenia[32]);
bool validUser(char user[100]);
bool validName(char name[60]);
bool repetition(FILE* fp, char user[100], struct usuarios usuario);
void Limpiar();
usuarios registrarAdmin(FILE* fp, struct usuarios usuario);
void registrarActividad(FILE* fp, Actividades actividad);
bool validTrainer(char actividad[100], char horario[50]);
bool validHourFormat(char hora[50]);
void calcularPago(entrenadores entrenador);